# Site settings
title: .NET DEVELOPLMENT
author: Kenny Tordeur
email: kenny.tordeur@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog.kennytordeur.be/" # the subpath of your site, e.g. /blog/
url: "http://kennytordeur.github.io/blog.kennytordeur.be/" # the base hostname & protocol for your site
twitter_username: kennytordeur
github_username:  kennytordeur

permalink: /post/:title

markdown: kramdown
highlighter: pygments
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

