# Site settings
title: Kenny Tordeur
author: Kenny Tordeur
email: kenny.tordeur@outlook.com
description: > # This is a place where i can write my thoughts about web development
keywords: "ASP.NET, C#, ASP.NET MVC, JAVASCRIPT, JQUERY"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kennytordeur.be" # the base hostname & protocol for your site
twitter_username: kennytordeur
github_username:  kennytordeur

permalink: /post/:title
 
#markdown: kramdown
#highlighter: pygments
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

markdown: redcarpet
redcarpet:
    extensions: ["tables"]
gems:
- jekyll-redirect-from
- jekyll-sitemap

